# Generated by Django 4.2.20 on 2025-04-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("pet_photo", models.URLField()),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Pets",
        ),
    ]
